service: forex

frameworkVersion: "<=1.6.1"

custom:
  namespace: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  environment:
    CLIENT_ID: '249416069520.269132431858'
    CLIENT_SECRET: 3be7d6259bdd57517a0223532d6bb7d4
    VERIFICATION_TOKEN: wDQYNOELhCv1NzG6UjQcC3GY
    INSTALL_ERROR_URL: http://krouze-webapp.s3-website-us-west-2.amazonaws.com/error.html
    INSTALL_SUCCESS_URL: http://krouze-webapp.s3-website-us-west-2.amazonaws.com/success.html
    NAMESPACE: ${self:custom.namespace}
    TEAMS_TABLE: ${self:custom.namespace}-teams
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.TEAMS_TABLE}

functions:
  install:
    handler: install.handler
    events:
      - http:
          path: install
          method: get
  events:
    handler: events.handler
    events:
      - http:
          path: events
          method: post

resources:
  Resources:
    TeamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEAMS_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
